GET http://localhost:3000

###login route
POST http://localhost:3000/auth/login

###Register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "karenmoneyyyyyyy@gmail.com",
     "password": "1234"
   
    
}
###refresh token route
POST http://localhost:3000/auth/refresh-token   


###logout route
DELETE  http://localhost:3000/auth/logout